apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: templatepriv
spec:
  params:
    - name: dummy
      default: prod
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipelinepriv

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bindingpriv
spec:
  params:
    - name: dummy
      value: "https://github.com/skaegi/hello-containers"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listenerprivgg
spec:
  triggers:
    - binding:
        name: bindingpriv
      template:
        name: templatepriv
    