apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: echo-listener
spec:
  triggers:
    - binding:
        name: echo-pipeline-binding
      template:
        name: echo-pipeline-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: echo-pipeline-binding
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: echo-pipeline-template
spec:
  params:
    - name: envTextProp1
      description: Env1 property
    - name: envTextareaProp1
      description: Env2 property
    - name: envSecureProp1
      description: Env3 property
    - name: envTextProp2
      description: Env4 property
    - name: envTextareaProp2
      description: Env5 property
    - name: envSecureProp2
      description: Env6 property
      default: --none--
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: echo-pipeline-run-
        labels:
          triggertemplated: "true"
          generatedBy: "echo-example"
      spec:
        pipelineRef:
          name: echo-props-pipeline
        params:
          - name: envTextProp1
            value: $(params.envTextProp1)
          - name: envTextareaProp1
            value: $(params.envTextareaProp1)
          - name: envSecureProp1
            value: $(params.envSecureProp1)
          - name: envTextProp2
            value: $(params.envTextProp2)
          - name: envTextareaProp2
            value: $(params.envTextareaProp2)
          - name: envSecureProp2
            value: $(params.envSecureProp2)
