apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "Pipeline Task1";
          echo "Using https://github.com/idsb3t1/KEEP-pipeline-tests-resources.git";
          echo "=======================";
          echo "IBM Cloud - Status - https://cloud.ibm.com";
          echo "=======================";
          sleep 10;
          alive=$(curl -s -o /dev/null -L -w %{http_code} https://cloud.ibm.com);
          if [ "$alive" == "200" ];
          then echo "TEST PASS - 200"; exit 0;
          else echo "TEST FAIL - $alive"; exit 1;
          fi
